apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: alameda-ai
  name: alameda-ai
  namespace: alameda
spec:
  replicas: 1
  selector:
    app: alameda-ai
    deploymentconfig: alameda-ai
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: alameda-ai
        deploymentconfig: alameda-ai
    spec:
      containers:
      - args:
        imagePullPolicy: Always
        name: alameda-ai
        ports:
        - containerPort: 50051
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: alameda-ai
      serviceAccountName: alameda-ai
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - alameda-ai
      from:
        kind: ImageStreamTag
        name: alameda-ai:latest
        namespace: alameda
    type: ImageChange
