apiVersion: v1
kind: Namespace
metadata:
  name: alameda
---
apiVersion: v1
kind: Service
metadata:
  name: alameda-ai
  namespace: alameda
  labels:
    app: alameda-ai
spec:
  selector:
    app: alameda-ai
  ports:
  - port: 50051
    name: grpc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alameda-ai
  namespace: alameda
