apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: alameda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-operator-role
subjects:
- kind: ServiceAccount
  name: operator
  namespace: alameda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: alameda-datahub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-datahub-role
subjects:
- kind: ServiceAccount
  name: datahub
  namespace: alameda

