---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: webapp
spec:
  ports:
  - name: redis-port
    port: 6379
  clusterIP: None
  selector:
    app: redis
    appCluster: redis-cluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: webapp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: webapp
  labels:
    app: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccount: redis
      containers:
      - name: redis
        image: redis:latest        
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: redis
          containerPort: 6379
          protocol: "TCP"